spring:
  application:
    name: BackgroundTrafficBot

server:
  port: 8070

request:
  # Valori: "generation", "upload"
  mode: "generation"
  generation: # [0, 23]
    start-hour: 0
    end-hour: 23
    generated-request-output: "./results/generated_requests.csv"

    # Distribuzione gaussiana per SOC target ricarica
    soc:
      target:
        mean: 0.65
        std-dev: 0.10
  upload:
    input: "./results/generated_requests.csv"
  execution-output: "./results/request_processing.csv"
  websocket:
    publish-interval-seconds: 45
