spring:
  application:
    name: BackgroundTrafficBot

server:
  port: 8070

request:
  # Valori: "generation", "upload"
  mode: "generation"
  generation:
    start-hour: 13
    end-hour: 23
    generated-request-output: "./results/generated_requests.csv"

    # Distribuzione gaussiana per SOC post-ricarica
    soc:
      target:
        mean: 0.65
        std-dev: 0.10
  upload:
    input: "/home/michele/IdeaProjects/bot/src/main/resources/csv/test/debug_requests1.csv"
  execution-output: "./results/request_processing.csv"
  websocket:
    publish-interval-seconds: 45